Refactor setup scripts

diff --git a/scripts/setup/executable_os b/scripts/setup/executable_os
--- a/scripts/setup/executable_os
+++ b/scripts/setup/executable_os
@@ -4,18 +4,14 @@ set -Eeuo pipefail
 
 setup_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
 
-script_dirs=(
-  "$setup_dir"
-)
-
 kernel_name="$(uname -s || true)"
 
 if [[ "$kernel_name" == "Darwin" ]]; then
-  script_dirs+=(
+  script_dirs=(
     "${setup_dir}/macos"
   )
 elif [[ "$kernel_name" == "Linux" ]]; then
-  script_dirs+=(
+  script_dirs=(
     "${setup_dir}/linux"
   )
 
@@ -26,6 +22,9 @@ elif [[ "$kernel_name" == "Linux" ]]; then
       "${setup_dir}/$(echo "$distro_id" | tr '[:upper:]' '[:lower:]')"
     )
   fi
+else
+  echo "Unknown kernel: aborting OS setup"
+  exit 1
 fi
 
 for dir in "${script_dirs[@]}"; do
@@ -33,7 +32,10 @@ for dir in "${script_dirs[@]}"; do
     echo "Running scripts from $(basename "$dir")"
 
     for script in $(find "$dir" -maxdepth 1 -type f -perm -500 \( -iname '*.sh' -or -iname '*.fish' \) | sort -n); do
+      echo "== [$(date +%H:%M:%S)] Running $script"
       "$script"
     done
+
+    echo "== [$(date +%H:%M:%S)] Finished."
   fi
 done
